export const createConst = (actionName) => {
  return {
    REQUEST: `${actionName}.REQUEST`,
    SUCCESS: `${actionName}.SUCCESS`,
    FAILURE: `${actionName}.FAILURE`,
  }
}

export const TOOLS = {
  SET_TOOL_NAME: 'SET_TOOL_NAME',
  LOAD_STOCKS_LIST: createConst('LOAD_STOCKS_LIST'),
  SAVE_DEFAULT_STOCKS_NAMES_LIST: 'SAVE_DEFAULT_STOCKS_NAMES_LIST',
  SAVE_SELECTED_COMPANY_NAME: 'SAVE_SELECTED_COMPANY_NAME',
  SAVE_SELECTED_COMPANY_STOCKS_LIST: 'SAVE_SELECTED_COMPANY_STOCKS_LIST',
  CLEAR_SELECTED_COMPANY_STOCKS_LIST: 'CLEAR_SELECTED_COMPANY_STOCKS_LIST',
  SAVE_CURRENT_RANGE: 'SAVE_CURRENT_RANGE',
  SAVE_CRYPTOCURRENCIES_DATA: 'SAVE_CRYPTOCURRENCIES_DATA'
}

export const SYMBOLS = {
  SAVE_LIST: 'SAVE_LIST'
}

export const PREDICTION = {
  SAVE_TRAINING_DAYS_AMOUNT: 'SAVE_TRAINING_DAYS_AMOUNT',
  SAVE_EPOCHS_AMOUNT: 'SAVE_EPOCHS_AMOUNT',
  SAVE_PREDICTED_PRICE: 'SAVE_PREDICTED_PRICE'
}

export const NEWS = {
  SAVE_MARKET_NEWS_LIST: 'SAVE_MARKET_NEWS_LIST',
  SAVE_COMPANY_NEWS_LIST: 'SAVE_COMPANY_NEWS_LIST',
  CLEAR_COMPANY_NEWS_LIST: 'CLEAR_COMPANY_NEWS_LIST',
  SAVE_COMPANY_SYMBOL: 'SAVE_COMPANY_SYMBOL'
}

export const IPO = {
  SAVE_TODAYS_LIST: 'SAVE_TODAYS_LIST',
  SAVE_UPCOMINGS_LIST: 'SAVE_UPCOMINGS_LIST',
  SELECT_IPO_INTERVAL: 'SELECT_IPO_INTERVAL'
}

export const AUTH = {
  SAVE_LOGGED_IN_USER: 'SAVE_LOGGED_IN_USER',
  SET_LOGIN_ERROR_MESSAGE: 'SET_LOGIN_ERROR_MESSAGE',
  CLEAR_LOGIN_ERROR_MESSAGE: 'CLEAR_LOGIN_ERROR_MESSAGE',
  LOGOUT: 'LOGOUT',
  SET_REGISTER_ERROR_MESSAGE: 'SET_REGISTER_ERROR_MESSAGE',
  CLEAR_REGISTER_ERROR_MESSAGE: 'CLEAR_REGISTER_ERROR_MESSAGE'
}