export const TOOLS_NAMES = {
    STOCKS: 'STOCKS',
    INDICES: 'INDICES',
    INDICES_FUTURES: 'INDICES_FUTURES',
    CURRENCIES: 'CURRENCIES',
    CRYPTOCURRENCIES: 'CRYPTOCURRENCIES',
    COMMODITIES: 'COMMODITIES'
}

export const TOOLS_TYPES = [
    TOOLS_NAMES.STOCKS,
    TOOLS_NAMES.INDICES,
    TOOLS_NAMES.INDICES_FUTURES,
    TOOLS_NAMES.CURRENCIES,
    TOOLS_NAMES.CRYPTOCURRENCIES,
    TOOLS_NAMES.COMMODITIES
]

export const DEFAULT_LOADED_STOCKS = ['AAPL', 'MSFT', 'FB', 'TSLA', 'AMZN']