export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  UNIVERSE: 'Universe',
  ABOUT_US: 'About Us',
  PRODUCTS: 'Products',
  CONTACT_US: 'Contact Us',
  UNIVERSE_PROJECT: 'Universe Project',
  PREDICT_PRICE_ON_STOCKS: 'Predict price on all stocks easily from anywhere you are',
  APP: 'App',
  STOCKS: 'Stocks',
  INDICES: 'Indices',
  INDICES_FUTURES: 'Indices Futures',
  COMMODITIES: 'Commodities',
  CURRENCIES: 'Currencies',
  CRYPTOCURRENCIES: 'Cryptocurrencies',
  CONTINUE: 'Continue',
  OPEN_STOCK_MARKET_TOOLS: 'Open Stock Market Tools',
  LOAD_STOCKS_SYMBOLS: 'Load Stocks Symbols List',
  COMING_SOON: 'Coming Soon',
  DATA_LOADING_ERROR: 'Data loading error!',
  SEARCH_COMPANY: 'Search a company',
  PREDICT_STOCKS_PRICE: 'Predict stocks price',
  TRAINING_DAYS: 'Training days',
  EPOCHS: 'Epochs',
  SELECT_PREDICTION_SETTINGS: 'Select prediction settings',
  STOCKS_PRICE_PREDICTION: 'Stocks Price Prediction',
  PREDICTED_STOCK_PRICE: 'Predicted Stock Price:',
  COMPANY_STOCKS_WILL_RISE: 'Company stocks will rise!',
  COMPANY_STOCKS_WILL_FALL: 'Company stocks will fall!',
  RAISING_DIFFERENCE: 'Raising difference:',
  USERNAME_OR_EMAIL: 'Username or email',
  EMAIL_PLACEHOLDER: 'username@mailaddress.com',
  PASSWORD: 'Password',
  PASSWORD_PLACEHOLDER: '********',
  REMEMBER_ME: 'Remember me',
  REGISTRATION: 'Registration',
  FIRSTNAME: 'Firstname',
  FIRSTNAME_PLACEHOLDER: 'John',
  LASTNAME: 'Lastname',
  LASTNAME_PLACEHOLDER: 'Smith',
  EMAIL: 'Email',
  CONFIRM_PASSWORD: 'Confirm password',
  ACCEPT_OUR_POLICY: 'Accept with our privacy policy',
  STOCK_MARKET: 'Stock Market',
  NEWS: 'News',
  COMPANIES_NEWS: 'Companies News',
  IPO_CALENDAR: 'IPO Calendar',
  TODAY_IPOS: 'Today IPOs',
  UPCOMING_IPOS: 'Upcoming IPOs',
  COMPANY: 'Company',
  SYMBOL: 'Symbol',
  MARKET: 'Market',
  PRICE: 'Price',
  AMOUNT: 'Amount',
  EXPECTED: 'Expected',
  INVALID_USERNAME_OR_PASSWORD: 'Invalid username or password!',
  WELCOME: 'Welcome, ',
  LOGOUT: 'Logout',
  USERNAME_IS_ALREADY_USED: 'Username is already used',
  TRAINING_REPEATS: 'Training repeats',
  SELECT_COMPANY: 'Select company:',
  SELECT_INTERVAL: 'Select interval:',
  MENU: 'Menu',
  GET_PREDICTION: 'Get prediction',
  SAVE_PREDICTION: 'Save prediction'
}