export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  UNIVERSE: 'Universe',
  ABOUT_US: 'About Us',
  PRODUCTS: 'Products',
  CONTACT_US: 'Contact Us',
  UNIVERSE_PROJECT: 'Universe Project',
  PREDICT_PRICE_ON_STOCKS: 'Predict price on all stocks easily from anywhere you are',
  APP: 'App',
  STOCKS: 'Stocks',
  INDICES: 'Indices',
  INDICES_FUTURES: 'Indices Futures',
  COMMODITIES: 'Commodities',
  CURRENCIES: 'Currencies',
  CRYPTOCURRENCIES: 'Cryptocurrencies',
  CONTINUE: 'Continue',
  OPEN_STOCK_MARKET_TOOLS: 'Open Stock Market Tools',
  LOAD_STOCKS_SYMBOLS: 'Load Stocks Symbols List',
  COMING_SOON: 'Coming Soon',
  DATA_LOADING_ERROR: 'Data loading error!',
  SEARCH_COMPANY: 'Search a company',
  PREDICT_STOCKS_PRICE: 'Predict stocks price',
  TRAINING_DAYS: 'Training days',
  EPOCHS: 'Epochs',
  SELECT_PREDICTION_SETTINGS: 'Select prediction settings',
  STOCKS_PRICE_PREDICTION: 'Stocks Price Prediction',
  PREDICTED_STOCK_PRICE: 'Predicted Stock Price:'
}